version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    links:
      - mysql:db

  minio:
    image: minio/minio
    container_name: minio-container
    command: server /data
    environment:
      MINIO_ACCESS_KEY: adminkey
      MINIO_SECRET_KEY: admin_key
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data:
